### ISSUE TITLE
Sound for seatbelt and no smoking switches?

### ISSUE THREAD

**Issue by triplesevenbob** [Dros0phila/C208-MSFS2020-Fix#10]
Very important if you can do this make a sound play when switching on and off the seat belt and smoking switch.  Thank you for this mod combined with the working title g1000 mod it is perfect!  :)

**Comment by Dros0phila** [comment]
I'd love to do that but I really don't know how to work with sounds in the sim yet. I'll focus on the main problems with the engine/fuel consumption/flight model first but in the future I do plan on improving the sounds. Thank you for using the mod!
