### ISSUE TITLE
Merge Uwajimaya's C208 lighting modifications into C208-MSFS20202-Fix

### ISSUE THREAD

**Issue by D33pfield** [Dros0phila/C208-MSFS2020-Fix#11]
I apologize if this isn't the correct way to suggest this. I'm not a C208 pilot so I can't confirm it is to world specs but the extra lighting is nice. As the lighting fix modifies systems.cfg I was able to merge them but It would require a hand merge each time you update that file. Maybe contact Uwajimaya to see if this is okay. The modification enhances the C208's landing, taxi and positional lighting. 

[Uwa light mod pack](https://github.com/Uwajimaya/FS2020)
![C208_1](https://user-images.githubusercontent.com/14086090/93926154-c79a3c00-fcdc-11ea-8373-4f0a00fc6a83.jpg)
![C208_2](https://user-images.githubusercontent.com/14086090/93926162-c963ff80-fcdc-11ea-9e30-89c8c8f76e40.jpg)

**Comment by D33pfield** [comment]
I've created a branch of this to see if you like it.
https://github.com/D33pfield/C208-MSFS2020-Fix/tree/Uwa-light-mod-merge

**Comment by Dros0phila** [comment]
Hey thanks for that! I did see his mod and was planning on adding it to the C208 mod, but as you said it would require an manual update of the systems.cfg each time he updates his mod (which isn't that big of a problem). Right now I'm trying to get the G1000 screens to start up the proper way, so I've made some changes to the electrical system in the systems.cfg, but even though I was able to make the reversionary mode functional and the left pfd turning on with Avionics 1 as in the real plane, I have somehow created a problem where all the screens have a strange white backlight (image bellow), as if they were really bright (decreasing the brightness doesn't solve the problem). This happens only when the reversionary mode is functional.
![image](https://user-images.githubusercontent.com/50115960/93968595-58563380-fd40-11ea-9961-c01d2324136a.png)

So I'm still trying to figure out how to solve it, but tomorrow I'll take a look at what you've done and message Uwajimaya to see if we can merge his mod with mine and release a new version with it. Thanks again, and if you have any idea of how to solve this screen problem I would really appreciate the help. I'll upload the WIP to the master branch soon so you can take a look if you want.

**Comment by D33pfield** [comment]
Sure I can take a look and see what I can do. I'm not super savvy with how things work yet though. I see the Dev upload now so ill give it a go! I am thinking its a conflict with Working Titles mod maybe.

**Comment by Dros0phila** [comment]
Yeah, I suspected that it might be a conflict with the g1000 mod too, but unfortunately it isn't. Uwajimaya said it's okay to merge his mod with ours, but he said he just updated the files so will make a new merge from v0.4.2 with the light mod.

**Comment by D33pfield** [comment]
Should I open a new issue for the white overlay when using ReversionaryMode Just to track a bit better?

**Comment by Dros0phila** [comment]
Yes please do that, I'll go ahead and close this one. Thanks.
