### ISSUE TITLE
Anti Ice Control is reversed. 

### ISSUE THREAD

**Issue by Bahnzo** [Dros0phila/C208-MSFS2020-Fix#16]
Most likely an issue with the stock plane and not the mod, but just in case and if it can be fixed.....

The switch for setting anti ice between the windshield and the airframe is reversed. If you set it to windshield, it does the airframe. You can verify this because not only doesn't it clean the windshield in icing conditions, but when you set it to windshield and turn on the icing, the plane pitches down as it sheds the icing from the wings. 

Not sure what would be best to fix this. I would prefer it be set in the plane itself rather than fixed with a change of the cockpit graphics (unless that's what the real plane looks like). 

Screenshot below! It's the "Max Flow - Airframe/Windshield" switch in the middle there. 

![20200928225107_1](https://user-images.githubusercontent.com/13858614/94520870-e8cdc180-01e1-11eb-8a3a-9b921145f852.jpg)

**Comment by Dros0phila** [comment]
Hi, thanks for the feedback. I don't know if you agree with me on that, but based on what I've seem so far in the simulator and everything I've studied/experienced in my short aviation career, the icing in MSFS is VERY badly simulated. Too much ice accumulates on the plane surfaces in conditions where you shouldn't expect icing at all. There's ice forming everywhere in the plane, even close to the engine exhaust. You get rime ice in conditions where you'd expect clear ice to build up. It seems like it's really exaggerated just for pretty visuals of icing conditions and for now I've just turned all the icing effects off in my simulator until this is fixed. But again, I might be wrong about that and would love to know what you think, and you're probably right about the de ice being inverted, and it shouldn't be hard to change that. I'll just check with a RL caravan pilot and try to make the changes. Thanks.

**Comment by Bahnzo** [comment]
I think you missed my entire point there. I have no issues with how the icing is implimented in the sim. I'm talking about the one switch being reversed on the plane. Please re-read my post above which explains that. And the pic I attached was to show the switch position.

**Comment by Exp232** [comment]
Did you notice the tooltip for this switch is correct? Sometimes switches like this are inverted, with the switch pointing to what's on instead of covering it. This might be intentional, should probably get feedback from a C208 pilot before attempting to switch it's input.

**Comment by Bahnzo** [comment]
It's either they have the labeling wrong in the cockpit, or the switch is functioning backwards. It makes zero sense to wire a switch that way, especially as there are no other switches in the 208 that are that way.

**Comment by Dros0phila** [comment]
I'm sorry, you're right, I might have missed your point. I think you're probably correct since, as you've said, the effect is contrary to what's written in each position of the switch. However, I'm not a real life Caravan pilot and I still haven't had time to read through the anti-ice section in the POH, so I don't really know the way the system should behave (or if it's even  close to the real thing in MSFS, since anti-ice systems are supposed to prevent ice build up and not remove it). I'm really sorry but I don't think I'll have the time to look into it for now, since I'm going through some problems in life and am currently far from home, so it might be some time until I can get into modding again. But anyway, thanks for the feedback and this problem will surely be among the fixes I'll work on as soon as I have the time. Don't forget that you or anyone else who knows how to code is more than welcome to help in the project with pull requests! :-)

**Comment by Dros0phila** [comment]
There are more tooltips that are wrong in the aircraft, the "mixture" one being one of the most noticeables. If you check the systems.cfg file you can see that the "de-ice" system is coded as a pneumatic leading edge air boot system, but for what I've read in the POH the plane actually has an anti-ice system, which is more complex than a pneumatic de-ice. So, what I'm trying to say here is that the anti-ice system is probably not only wrong - it's most likely not even simulated. This would require custom coding to implement a proper anti-ice system, which is way beyond my skills and would also be affected by the poorly simulated icing in the base sim right now. So, for now unfortunately this isn't really a priority, and if I don't get help I don't even think that I'll be able to fix it alone.

**Comment by Bahnzo** [comment]
Again you are missing my point here. I don't care about whether the anti ice system is simulated properly or not, or if the plane uses the boots vs the liquid system. That's something Asobo will need to fix in time.

It's simply there's a switch which is inverted. I thought that might be easy to fix.

**Comment by Dros0phila** [comment]
![IMG_20200929_160942](https://user-images.githubusercontent.com/50115960/94604582-460f5480-026e-11eb-96f1-be8f3f35f780.jpg)
As you can see in this pic of the real plane, the labeling is not wrong, so it's probably the system logic that is inverted. You're welcome to change that if you want, it's probably easy.
