### ISSUE TITLE
Ground idle too high

### ISSUE THREAD

**Issue by AndersHogqvist** [Dros0phila/C208-MSFS2020-Fix#4]
She starts rolling as soon as you release the brakes, even on low idle. During taxi you need to hit the brakes occasionally to avoid getting a speed ticket from airport police :-)

This causes problem on pushback as well since you run over the push back vehicle as soon as you release the brakes.

**Comment by AndersHogqvist** [comment]
I just read on the forum that this might be accurate. Some pilots explained how they use the beta range to slow the airplane down while taxing.

However, I think it shouldn't start rolling when you hit the brakes.

**Comment by Dros0phila** [comment]
Thank you for the info! I do agree that the plane starts rolling way too fast. The ground idle is a problem I'm looking into. There's also a bigger problem that is related to it: the beta range in the power lever isn't simulated in an accurate way (actually the reverse thrust also doesn't work). This problem with the beta range is very hard to deal with using only the .cgf files of the engine parameters, and I'm still trying to understand the SDK. Soon I'll have a real C208B pilot testing the aircraft and I'll try to fix at least the ground idle issue in the next update, along with some flight model adjustments based on the feedback I get. Thanks again.

**Comment by Dros0phila** [comment]
This should be fixed with the latest update.
