### ISSUE TITLE
Cruise fuel flow too high

### ISSUE THREAD

**Issue by brandon-jardine** [Dros0phila/C208-MSFS2020-Fix#6]
Some of the cruise settings listed in the POH produce speeds ~10% quicker than those listed.

The fuel flow is also significantly higher in the sim than the values listed in the POH.

I don't expect that the performance in the sim will ever match the POH exactly (nor would I expect a real aircraft to), but the fuel flow in particular seems like it should be tweaked some more.

![MSFS](https://user-images.githubusercontent.com/15150911/92681178-94c27200-f2f2-11ea-9997-143b7adbe386.png)
![POH](https://user-images.githubusercontent.com/15150911/92681189-9be98000-f2f2-11ea-84ab-1bb4862d376f.png)

**Comment by Dros0phila** [comment]
Thanks for the info! I still haven't had the time to test all of the cruise RPM settings (I usually test with 1750 and 1900 rpm) so your feedback is very valuable. I'll try to focus on this fuel/excessive cruise power problem so it works well enough with all the cruise settings.

**Comment by Dros0phila** [comment]
Hey, I've released a new version where the fuel consumption should be closer to what what the POH says. I still can't get it to be as low as it should at FL180 and above, but in my short test flights it was acceptable in lower levels (FF a little lower than what it is in the POH), so while it still isn't as precise as I'd like at least you won't end up with an empty tank in the middle of the flight!
