### ISSUE TITLE
Max Torque set to 1865 in engine.cfg, however G1000 Panel is not correct

### ISSUE THREAD

**Issue by Matchrocket** [Dros0phila/C208-MSFS2020-Fix#8]
I'm not sure this really matters right now given how jacked up the Engine logic is in-game, but the max torque is not reflected on the G1000 in the panel.xml file (Asobo_208B_GRAND_CARAVAN_EX\panel)

Adjusting this down to this limit would result in severely underpowered take-off's, however, based on my testing. Not sure if this is due to engine logic or something else. 

Cruse Example Currently:
60% power @ 7400 ft OAT 15c = 1900 ft-lbs of torque @ 555c ITT. 

	<EngineDisplay>
		<Gauge>
			<Type>Circular</Type>
			<Style>
				<BeginAngle>-50</BeginAngle>
				<EndAngle>190</EndAngle>
				<ValuePos>End</ValuePos>
				<CursorType>Triangle</CursorType>
				<SizePercent>90</SizePercent>
			</Style>
			<BeginText></BeginText>
			<EndText></EndText>
			<ID>Turbo_TorqueGauge</ID>
			<Title>TRQ</Title>
			<Unit>FT-LB</Unit>
			<Minimum>0</Minimum>
			<Maximum>2600</Maximum>
			<Value>
				<Simvar name="TURB ENG FREE TURBINE TORQUE:1" unit="Foot pounds"/>
			</Value>
			<ColorZone>
				<Color>green</Color>
				<Begin>0</Begin>
				<End>2396</End>
			</ColorZone>
			<ColorZone>
				<Color>red</Color>
				<Begin>2396</Begin>
				<End>2600</End>
			</ColorZone>
			<GraduationLength>100</GraduationLength>
			<GraduationTextLength>500</GraduationTextLength>
			<RedBlink>
				<Greater>
					<Simvar name="ENG TORQUE:1" unit="Foot pounds"/>
					<Constant>2400</Constant>
				</Greater>
			</RedBlink>
		</Gauge>

**Comment by Dros0phila** [comment]
Yes, I'm aware of this but thanks for point that out anyways. But as you've said, the engine logic is really messed up, to an extent in which I don't really think I can do much more with my poor programming skills. I decided to just wait and see how Asobo will deal with these turboprop situation first.

**Comment by Dros0phila** [comment]
Even though the max TRQ by the POH is around 1850 ft-lbs, the TRQ indicator green area goes all the way to 2300 ft-lbs. I plan to correct this in the G1000 MFD and in the STBY TRQ indicator, which is also wrong.
