### ISSUE TITLE
The mod doesn't seem to work after latest patch

### ISSUE THREAD

**Issue by AndersHogqvist** [Dros0phila/C208-MSFS2020-Fix#9]
Just installed the latest patch and took off. The mod doesn't seem to work at all now.

**Comment by AndersHogqvist** [comment]
A restart fixed it

**Comment by Dros0phila** [comment]
There are some problems to the mod that came with the latest update. I'm trying to make a version that works fine but it might take some time to get it stable. I'll update the files in the master branch so other users can test it as well.
